### USER REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "andrea@gmail.com",
    "password": "1234"
}

### USER LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "andrea@gmail.com",
    "password": "1234"
}

### USER LOGOUT
GET http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: 

### USER DELETE
DELETE http://localhost:3000/user/:referenceKeyUser
Content-Type: application/json
Authorization: 924b36f11d151

### USER UPDATE
PUT http://localhost:3000/user/:referenceKeyUser
Content-Type: application/json
Authorization: 924b36f11d151

{
    "username": "Bambinobellissimo"
}
### READ USERS LIST

GET http://localhost:3000/users
Content-Type: application/json

### CREATE AD
POST http://localhost:3000/ads
Content-Type: application/json
Authorization: 7a741cc2c8d5b

{
  "title": "Calzini sporchissimi",
  "description": "Vendo calzini usati pieni di sudore, effettivamente fanno davvero schifo",
  "price": "20€",
  "category": "Vestiti",
  "condition": "Usato",
  "URLimage": "https://thumbs.dreamstime.com/z/calzini-sporchi-puzzolente-isolati-sui-precedenti-bianchi-42194500.jpg",
  "address": "Via santoro, 44"
}

### UPDATE AD
PATCH http://localhost:3000/ads/2a37321e9253a
Content-Type: application/json
Authorization: c08426caf56e8

{
  "title": "Calzini puliti",
  "description": "Vendo calzini come nuovi, effettivamente sono davvero comodi",
  "price": "54€",
  "category": "Vestiti",
  "condition": "Buono",
  "URLimage": "https://shop.bestsub.it/data/gfx/pictures/medium/6/1/5416_1.jpg",
  "address": "Via santoro, 42"
}

### READ ADS LIST
GET http://localhost:3000/ads
Content-Type: application/json

### READ AD DETAIL
GET http://localhost:3000/ads/d013a330bc6c

### DELETE AD
DELETE http://localhost:3000/ads/821aa1a79e01c
Content-Type: application/json
Authorization: 583de854ae9dd

### READ REVIEW LIST
GET http://localhost:3000/reviews
Content-Type: application/json

### CREATE REVIEW
POST http://localhost:3000/reviews/5dfe6442e1d1a
Content-Type: application/json
Authorization: 80e5b2cdb9782

{
  "title": "Davvero serio",
  "description": "incredibile serietà e disponibilità",
  "rating": 5
}

### UPDATE REVIEW
PATCH http://localhost:3000/reviews/e720da7d0ec4c
Content-Type: application/json
Authorization: a34f46794322b

{
  "title": "Bruttissimo",
  "description": "Per niente serio, vergogna!",
  "rating": 1
}

### DELETE REVIEW
DELETE http://localhost:3000/reviews/5dfe6442e1d1a
Content-Type: application/json
Authorization: 80e5b2cdb9782

### GET CATEGORY LIST
GET http://localhost:3000/ads/category/Vestiti
Content-Type: application/json


### MARK AS SOLD 
POST http://localhost:3000/ads/bc44b29b6966
Content-Type: application/json
Authorization: 7a741cc2c8d5b

{
  "sold": "bfc152b27ef21"
}


### BOUGHT LIST
GET http://localhost:3000/user/ads/bought
Content-Type: application/json
Authorization: 7a741cc2c8d5b